-- ============================================================
-- LAYAG: Courier and Logistics Tracking System
-- Database setup script (MySQL)
-- Run in phpMyAdmin (SQL tab) or: mysql -u root < schema.sql
--
-- Creates: couriersystem database
--          users, parcels, status_history tables
-- ============================================================

CREATE DATABASE IF NOT EXISTS couriersystem;
USE couriersystem;

-- ------------------------------------------------------------
-- users: system accounts with role-based access
-- Roles: SENDER, RECEIVER, COURIER, BRANCH_STAFF, ADMIN
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id       INT AUTO_INCREMENT PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(50)  NOT NULL DEFAULT 'SENDER'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- parcels: registered shipments.
-- fee = computed at registration (weight tier x service x vehicle x zone + distance)
-- vehicle_type: MOTORCYCLE (0.8), VAN (1.0), MINIVAN (1.2), TRUCK (1.5)
-- tracking_code: public code given to the sender (LAYAG-XXXX-XXXX-XXXX).
--                Generated by ParcelService; unique so it never collides.
-- created_by_user_id: the account that booked the parcel (owner checks).
-- confirmed: sender verified the details/weight before pickup (spec: Confirm Parcel).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parcels (
    parcel_id      INT AUTO_INCREMENT PRIMARY KEY,
    sender_name    VARCHAR(100) NOT NULL,
    receiver_name  VARCHAR(100) NOT NULL,
    weight_kg      DOUBLE NOT NULL,
    current_status VARCHAR(50)  NOT NULL DEFAULT 'REGISTERED',
    fee            DOUBLE NOT NULL DEFAULT 0,
    vehicle_type   VARCHAR(50)  NOT NULL DEFAULT 'VAN',
    tracking_code  VARCHAR(30)  NOT NULL UNIQUE,
    service_type   VARCHAR(20)  NOT NULL DEFAULT 'regular',
    created_by_user_id INT NULL,
    pick_up_address   VARCHAR(255) NULL,
    drop_off_address  VARCHAR(255) NULL,
    distance_km       DOUBLE NOT NULL DEFAULT 0,
    inter_island      TINYINT(1) NOT NULL DEFAULT 0,
    confirmed         TINYINT(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- rider_profiles: one row per courier account (role = COURIER).
-- Riders are provisioned by admins - public sign-up can never pick
-- this role (trusted-role model). Availability + concurrent capacity
-- drive the auto-assignment algorithm.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rider_profiles (
    rider_user_id  INT PRIMARY KEY,
    vehicle_type   VARCHAR(50) NOT NULL DEFAULT 'MOTORCYCLE',
    is_available   TINYINT(1)  NOT NULL DEFAULT 1,
    max_concurrent INT NOT NULL DEFAULT 3,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- parcel_assignments: one pending/active assignment per parcel.
-- parcel_id is UNIQUE so a parcel can never be double-booked.
-- status: ASSIGNED -> ACCEPTED -> COMPLETED   (DECLINED/FAILED on
-- decline/exception). COMPLETED drives rider earnings.
-- decided_at/completed_at are set when the rider decides/completes.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parcel_assignments (
    assignment_id INT AUTO_INCREMENT PRIMARY KEY,
    parcel_id     INT NOT NULL UNIQUE,
    rider_user_id INT NOT NULL,
    status        VARCHAR(20) NOT NULL DEFAULT 'ASSIGNED',
    reason        VARCHAR(255) NULL,
    assigned_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    decided_at    TIMESTAMP NULL,
    completed_at  TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- ratings: one review per parcel (sender after delivery).
-- parcel_id is UNIQUE so each delivery is reviewed at most once.
-- rider_user_id denormalised from the assignment so the query path
-- stays simple (no join needed for per-rider averages).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ratings (
    rating_id      INT AUTO_INCREMENT PRIMARY KEY,
    parcel_id      INT NOT NULL UNIQUE,
    user_id        INT NOT NULL,
    rider_user_id  INT NOT NULL,
    rating         INT NOT NULL,
    comment        VARCHAR(500) NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- notifications: in-app alert per user (the spec wants in-app + email;
-- the email leg is fired by NotificationService when a Mailer is set).
-- Types: PARCEL_STATUS, ASSIGNMENT, PAYMENT, SYSTEM.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notifications (
    notification_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id         INT NOT NULL,
    type            VARCHAR(30) NOT NULL,
    title           VARCHAR(150) NOT NULL,
    message         VARCHAR(500) NOT NULL,
    is_read         TINYINT(1) NOT NULL DEFAULT 0,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_user (user_id, is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- delivery_proofs: photograph + metadata proving the drop-off.
-- One proof per parcel (parcel_id UNIQUE); a later upload overwrites
-- the earlier one. photo_name points at the file on disk (proofs/).
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS delivery_proofs (
    proof_id       INT AUTO_INCREMENT PRIMARY KEY,
    parcel_id      INT NOT NULL UNIQUE,
    rider_user_id  INT NOT NULL,
    photo_name     VARCHAR(255) NOT NULL,
    notes          VARCHAR(255) NULL,
    recipient_name VARCHAR(100) NULL,
    delivered_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- status_history: the tracking timeline.
-- One row per status change; never overwritten.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS status_history (
    history_id INT AUTO_INCREMENT PRIMARY KEY,
    parcel_id  INT NOT NULL,
    status     VARCHAR(50)  NOT NULL,
    location   VARCHAR(100) NULL,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NULL,
    CONSTRAINT fk_status_parcel
        FOREIGN KEY (parcel_id) REFERENCES parcels (parcel_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- locations: GPS tracking points (lat/lng per parcel).
-- Backend stores pings; frontend draws them on a map.
-- Simulated in demo (real Rizal route); production = device pings.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS locations (
    location_id INT AUTO_INCREMENT PRIMARY KEY,
    parcel_id   INT NOT NULL,
    latitude    DOUBLE NOT NULL,
    longitude   DOUBLE NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_location_parcel
        FOREIGN KEY (parcel_id) REFERENCES parcels (parcel_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- payments: one transaction per parcel.
-- method: COD (cash on delivery, collected at drop-off)
--         ONLINE (mock e-wallet gateway, paid at checkout)
-- status: PENDING -> COMPLETED (paid_at set) | FAILED | REFUNDED
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    payment_id INT AUTO_INCREMENT PRIMARY KEY,
    parcel_id  INT NOT NULL,
    amount     DOUBLE NOT NULL,
    method     VARCHAR(20) NOT NULL,
    status     VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    reference  VARCHAR(50) NULL,
    paid_at    TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_parcel
        FOREIGN KEY (parcel_id) REFERENCES parcels (parcel_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Optional seed: a default ADMIN account.
-- NOTE: password_hash below is SHA-256 of "admin123".
-- Generated by AuthService (do NOT store plain-text passwords).
-- ------------------------------------------------------------
-- INSERT INTO users (name, email, password_hash, role) VALUES
--   ('System Admin', 'admin@layag.ph',
--    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'ADMIN');