-- ============================================================
-- LAYAG: Courier and Logistics Tracking System
-- Database setup script (MySQL)
-- Run in phpMyAdmin (SQL tab) or: mysql -u root < schema.sql
--
-- Creates: couriersystem database
--          users, parcels, status_history tables
-- ============================================================

CREATE DATABASE IF NOT EXISTS couriersystem;
USE couriersystem;

-- ------------------------------------------------------------
-- users: system accounts with role-based access
-- Roles: SENDER, RECEIVER, COURIER, BRANCH_STAFF, ADMIN
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    user_id       INT AUTO_INCREMENT PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    email         VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(50)  NOT NULL DEFAULT 'SENDER'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- parcels: registered shipments.
-- fee = computed at registration (weight tier x service x vehicle x zone)
-- vehicle_type: MOTORCYCLE (0.8), VAN (1.0), MINIVAN (1.2), TRUCK (1.5)
-- tracking_code: public code given to the sender (LAYAG-XXXX-XXXX-XXXX).
--                Generated by ParcelService; unique so it never collides.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parcels (
    parcel_id      INT AUTO_INCREMENT PRIMARY KEY,
    sender_name    VARCHAR(100) NOT NULL,
    receiver_name  VARCHAR(100) NOT NULL,
    weight_kg      DOUBLE NOT NULL,
    current_status VARCHAR(50)  NOT NULL DEFAULT 'REGISTERED',
    fee            DOUBLE NOT NULL DEFAULT 0,
    vehicle_type   VARCHAR(50)  NOT NULL DEFAULT 'VAN',
    tracking_code  VARCHAR(30)  NOT NULL UNIQUE,
    service_type   VARCHAR(20)  NOT NULL DEFAULT 'regular'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- status_history: the tracking timeline.
-- One row per status change; never overwritten.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS status_history (
    history_id INT AUTO_INCREMENT PRIMARY KEY,
    parcel_id  INT NOT NULL,
    status     VARCHAR(50)  NOT NULL,
    location   VARCHAR(100) NULL,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100) NULL,
    CONSTRAINT fk_status_parcel
        FOREIGN KEY (parcel_id) REFERENCES parcels (parcel_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- locations: GPS tracking points (lat/lng per parcel).
-- Backend stores pings; frontend draws them on a map.
-- Simulated in demo (real Rizal route); production = device pings.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS locations (
    location_id INT AUTO_INCREMENT PRIMARY KEY,
    parcel_id   INT NOT NULL,
    latitude    DOUBLE NOT NULL,
    longitude   DOUBLE NOT NULL,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_location_parcel
        FOREIGN KEY (parcel_id) REFERENCES parcels (parcel_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- payments: one transaction per parcel.
-- method: COD (cash on delivery, collected at drop-off)
--         ONLINE (mock e-wallet gateway, paid at checkout)
-- status: PENDING -> COMPLETED (paid_at set) | FAILED | REFUNDED
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
    payment_id INT AUTO_INCREMENT PRIMARY KEY,
    parcel_id  INT NOT NULL,
    amount     DOUBLE NOT NULL,
    method     VARCHAR(20) NOT NULL,
    status     VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    reference  VARCHAR(50) NULL,
    paid_at    TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_parcel
        FOREIGN KEY (parcel_id) REFERENCES parcels (parcel_id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ------------------------------------------------------------
-- Optional seed: a default ADMIN account.
-- NOTE: password_hash below is SHA-256 of "admin123".
-- Generated by AuthService (do NOT store plain-text passwords).
-- ------------------------------------------------------------
-- INSERT INTO users (name, email, password_hash, role) VALUES
--   ('System Admin', 'admin@layag.ph',
--    '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9', 'ADMIN');