spring.application.name=rizal-courier
spring.datasource.url=jdbc:mysql://localhost:3306/rizal_courier_db
spring.datasource.username=root
spring.datasource.password=rizal123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081